version: '3.9'

services:
  localssl-exporter:
    image: localssl-exporter:v1.0
    # environment:
    #   - METRICS_PORT=9006
    volumes:
      - /etc/certs:/etc/certs:ro
    ports:
      - "9999:9999"
    #   - "9006:9006"