version: '3.9'

services:
  localcert-exporter:
    image: localcert-exporter:v1.0
    # environment:
    #   - METRICS_PORT=9006
    volumes:
      - /etc/certs:/etc/certs:ro
    ports:
        - target: 9999
          published: 9999
    #     - target: 9006
    #       published: 9006        
    deploy:
      mode: global
      resources:
          limits:
              cpus: '1'
              memory: 256M
