version: "3.9"
services:
  shell-exporter:
    image: hetimop/localcert-exporter:v1.0
    environment:
      - METRICS_PORT=9006
    ports:
      - target: 9006 
        published: 9006 
        mode: host
    volumes:
      - /etc/certs:/etc/certs 
    deploy:
      mode: global
      resources:
          limits:
              cpus: '1'
              memory: 256M
